INSERT INTO `capabilities` (`id`, `name`) VALUES (1, N'Operational');
INSERT INTO `capabilities` (`id`, `name`) VALUES (2, N'Industrial');
INSERT INTO `capabilities` (`id`, `name`) VALUES (3, N'Applications');
INSERT INTO `capabilities` (`id`, `name`) VALUES (4, N'Telephony');
INSERT INTO `capabilities` (`id`, `name`) VALUES (5, N'Networking');
INSERT INTO `capabilities` (`id`, `name`) VALUES (6, N'Data Center');

INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (1, 1, N'Vertical Enterprise');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (2, 1, N'Site Surveys');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (3, 1, N'Cabling');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (4, 1, N'Edge Sensors');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (5, 1, N'MRO');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (6, 2, N'Operational Stack');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (7, 2, N'Point Solutions, e.g. SCADA');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (8, 2, N'Purdue Model');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (9, 2, N'Electrical - Mechanical - Chemical Engineers, etc.');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (10, 2, N'Circuit Design/Build');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (11, 2, N'IoT Platform Dev.');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (12, 3, N'Office 356, ERP/SCM, Vertical, etc.');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (13, 3, N'DevOps, Containers');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (14, 3, N'AWS, Azure Dev/Production');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (15, 3, N'IoT Platform Dev.');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (16, 3, N'Business Intelligence (BI)');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (17, 4, N'On-prem PBX');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (18, 4, N'Cabling, Batteries');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (19, 4, N'Wireless');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (20, 4, N'Unified Comms');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (21, 4, N'Voice & Data');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (22, 4, N'Managed PBX');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (23, 5, N'Routers, Hubs');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (24, 5, N'Security');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (25, 5, N'SDN, SD WAN');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (26, 5, N'Unified Comms');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (27, 5, N'Comm as a Service');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (28, 6, N'Servers');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (29, 6, N'Storage');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (30, 6, N'Systems Mgt. Software');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (31, 6, N'VDI, Business Intelligence (BI)');
INSERT INTO `stacks` (`id`, `capability_id`, `name`) VALUES (32, 6, N'IaaS, BDR, etc.');